name: sci
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - blas=1.0
  - bottleneck=1.4.2
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - et_xmlfile=1.1.0
  - expat=2.7.1
  - libcxx=14.0.6
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libmpdec=4.0.0
  - libopenblas=0.3.29
  - llvm-openmp=14.0.6
  - ncurses=6.4
  - numexpr=2.10.1
  - numpy=2.2.5
  - numpy-base=2.2.5
  - openpyxl=3.1.5
  - openssl=3.0.16
  - pandas=2.2.3
  - pip=25.1
  - python=3.13.2
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.2
  - python_abi=3.13
  - pytz=2024.1
  - readline=8.2
  - setuptools=72.1.0
  - six=1.17.0
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2025b
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - blinker==1.9.0
      - certifi==2025.4.26
      - charset-normalizer==3.4.2
      - click==8.2.1
      - dash==3.0.4
      - flask==3.0.3
      - idna==3.10
      - importlib-metadata==8.7.0
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - markupsafe==3.0.2
      - narwhals==1.41.0
      - nest-asyncio==1.6.0
      - packaging==25.0
      - plotly==6.1.2
      - requests==2.32.3
      - retrying==1.3.4
      - typing-extensions==4.13.2
      - urllib3==2.4.0
      - werkzeug==3.0.6
      - zipp==3.22.0
